"""empty message

Revision ID: 1c02764cb65f
Revises: 4aa3f4b7236e
Create Date: 2019-02-19 19:27:44.181326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c02764cb65f'
down_revision = '4aa3f4b7236e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('pref', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_prefs')
    # ### end Alembic commands ###
