"""empty message

Revision ID: 9b7e602091a6
Revises: 305ad51de9f5
Create Date: 2019-01-24 12:27:14.644583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7e602091a6'
down_revision = '305ad51de9f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('primary', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'primary')
    # ### end Alembic commands ###
